name = "RData"
uuid = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
version = "0.7.2"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
CategoricalArrays = "0.8"
CodecZlib = "0.4, 0.5, 0.6, 0.7"
DataFrames = "0.21"
FileIO = "1.0.5"
Requires = "1.0.0"
TimeZones = "0.7, 0.8, 0.9, 0.10, 1.0"
julia = "1"

[extras]
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
CodecXz = "ba30903b-d9e8-5048-a5ec-d1f5b0d4b47b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CodecBzip2", "CodecXz", "Test"]
